
import java.awt.Graphics;
import java.awt.Image;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewApplet.java
 *
 * Created on Nov 14, 2013, 6:09:40 PM
 */

/**
 *
 * @author PRavi
 */
public class NewApplet extends java.applet.Applet {
static Image img;
    /** Initializes the applet NewApplet */
    public void init() {
        img=getImage(getCodeBase(),"back.jpg");

        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }}
        public void paint(Graphics g)
        {
            g.drawImage(img,0,90,this);
        }

    

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
